import {
  Button,
  Container,
  Grid,
  Link,
  TextField,
  Typography,
} from "@mui/material";
import ArrowRight from "@mui/icons-material/ArrowRightAlt";
import CopyButton from "@mui/icons-material/ContentCopy";
import GithubButton from "@mui/icons-material/GitHub";
import type { NextPage } from "next";
import Head from "next/head";
import { ChangeEventHandler, useState } from "react";
import LinkModel from "../models/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [url, setUrl] = useState("");

  const t: LinkModel = {
    id: "https://l.larssonoliver.com/abcdef",
    url: "https://blog.logrocket.com/implementing-copy-to-clipboard-in-react-with-clipboard-api/",
  };

  const onChange: ChangeEventHandler<HTMLInputElement> = (e) => {
    const val = e.target.value;
    setUrl(val);
  };

  const onClick = () => {
    alert(url);
  };

  const onCopy = async () => {
    if ("clipboard" in navigator)
      return await navigator.clipboard.writeText(url);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography variant="h1" component="div">
          lnkshrt
        </Typography>

        <Typography variant="h5" component="div" marginBottom={"2em"}>
          an open source url shortener
        </Typography>

        <Container maxWidth="md">
          <Grid container spacing={2}>
            <Grid item xs={12} sm={9} md={10}>
              <TextField
                label="URL"
                fullWidth
                value={url}
                onChange={onChange}
                onKeyPress={(e) => {
                  if (e.key === "Enter") {
                    onClick();
                  }
                }}
              />
            </Grid>
            <Grid item xs={12} sm={3} md={2}>
              <Button
                variant="outlined"
                style={{ padding: "14.75px 14px" }}
                fullWidth
                onClick={onClick}
                disabled={url === ""}
              >
                Shorten
              </Button>
            </Grid>
          </Grid>

          {t.id && (
            <Container
              maxWidth="md"
              style={{
                border: "1px solid #eaeaea",
                borderRadius: "5px",
                margin: "1rem 0",
                padding: "1.5rem",
              }}
            >
              <Typography
                variant="body2"
                component="div"
                style={{
                  color: "gray",
                  wordBreak: "break-all",
                  marginBottom: "1rem",
                }}
              >
                {t.url}
              </Typography>

              <Typography
                variant="h6"
                component="div"
                style={{ display: "flow-root" }}
              >
                <div style={{ float: "left" }}>
                  <ArrowRight
                    color="disabled"
                    style={{
                      position: "relative",
                      top: "5px",
                      marginRight: "1rem",
                    }}
                  />
                  <Link
                    href=""
                    underline="none"
                    style={{
                      overflowX: "hidden",
                      wordBreak: "break-all",
                    }}
                  >
                    {t.id}
                  </Link>
                </div>
                <Button
                  variant="outlined"
                  style={{ float: "right" }}
                  onClick={onCopy}
                >
                  Copy link
                  <CopyButton style={{ marginLeft: "1rem" }} />
                </Button>
              </Typography>
            </Container>
          )}
        </Container>

        <Link
          color="primary"
          style={{ position: "absolute", right: "1em", bottom: "1em" }}
          href="https://github.com/larssonoliver/lnkshrt"
        >
          <GithubButton />
        </Link>

        {/* <form className={styles.card}>
            <input type='text' value={url} onChange={onChange}></input>
            <input type='submit'></input>
          </form> */}
        {/* <a href='https://nextjs.org/docs' className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href='https://github.com/vercel/next.js/tree/canary/examples'
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
      </main>

      {/* <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
