name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Verify Dependencies
        run: go mod verify

      - name: Build
        run: sh scripts/build.sh

  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Verify Dependencies
        run: go mod verify

      - name: Test
        run: sh scripts/test.sh

  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Verify Dependencies
        run: go mod verify

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          skip-cache: true