name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Verify Dependencies
        run: go mod verify

      - name: Tidy Dependencies
        run: go mod tidy
 
      - name: Build
        run: sh scripts/build.sh

  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Verify Dependencies
        run: go mod verify

      - name: Tidy Dependencies
        run: go mod tidy

      - name: Test
        run: sh scripts/test.sh

  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Verify Dependencies
        run: go mod verify

      - name: Tidy Dependencies
        run: go mod tidy
 
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout 5m
          skip-go-installation: true
