name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lnkshrt-build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
          check-latest: true

      - name: Build
        working-directory: lnkshrt
        run: go build -v ./...

  gui-build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Dependency Install
        working-directory: gui
        run: npm ci

      - name: Build
        working-directory: gui
        run: npm build

      - name: Lint
        working-directory: gui
        run: npm lint
