name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: sh scripts/test.sh

      - name: Build
        run: sh scripts/build.sh

  lnkshrt-gui-build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Dependency Install
        working-directory: web/lnkshrt-gui
        run: npm ci

      - name: Build
        working-directory: web/lnkshrt-gui
        run: npm run build

      - name: Lint
        working-directory: web/lnkshrt-gui
        run: npm run lint
