name: Build Release Images

on:
  create:
    tags:
      - v*.*.*

defaults:
  run:
    working-directory: lnkshrt

jobs:
  bake:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set TAG environment variable
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create docker context
        run: docker context create builders

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: docker buildx bake --push --print
        working-directory: lnkshrt
